#!/usr/bin/env bash
# Author: https://github.com/nntrn
# Repository: https://github.com/nntrn/queryibooks

set -e

DATE="$(date '+%F-%H-%M')"
TMPDIR=$(mktemp -d)
DOWNLOAD_DIR=$HOME/Downloads
ZIPFILENAME=ibooks-dayone-${DATE}.zip
SCRIPT=$(realpath $0)
DIR=${SCRIPT%/*}

trap 'rm -r "$TMPDIR"' EXIT

if ! command -v jq &>/dev/null; then
  echo "Download jq before continuing.. Aborting"
  exit 1
fi

cat $1 | jq -L $DIR 'include "queryibooks"; create_dayone_import' >$TMPDIR/ibooks.json

cd $TMPDIR && zip -q -r $DOWNLOAD_DIR/$ZIPFILENAME .

echo -e "
Done!
Import \e[0;49;33m${DOWNLOAD_DIR}/${ZIPFILENAME}\e[0m to Day One
" 3>&2 2>&1 >&3 3>&-
