#!/usr/bin/env bash
# Author: https://github.com/nntrn
# Repository: https://github.com/nntrn/queryibooks

set -e

DATE="$(date '+%F-%H-%M')"
TMPDIR=$(mktemp -d)
DOWNLOAD_DIR=$HOME/Downloads
ZIPFILENAME=ibooks-dayone-${DATE}.zip

trap 'rm -r "$TMPDIR"' EXIT

JQ_FUNC='
  def h2:
    if ((.|type) == "string" and (.|gsub(" "; "")? // ""|length) > 0)
    then "\n\n---\n\n## \(. | gsub("…";"."))\n"
    else "\n---\n"
    end;

  def remove_citations:
    gsub("[\\n]{2,}";"\n\n") | gsub("(?<a>[^ \n])[0-9]+\n"; "\(.a)\n"; "m");

  def create_dayone_import:
    map(. + (.ZANNOTATIONLOCATION|capture("\\[(?<chapter>[^\\]]+)\\].*/(?<location>.*)\\)" )))
    | map(select((.ZTITLE) and (.ZANNOTATIONSELECTEDTEXT|length) >10 ))
    | sort_by(.ZANNOTATIONLOCATION)
    | group_by(.ZSORTTITLE)
    | map(select(length>1))
    | map({
        title: .[0].ZTITLE,
        author: .[0].ZAUTHOR,
        uuid: (.[0].ZASSETGUID|gsub("-";"")? // ""),
        creationDate: min_by(.ZANNOTATIONCREATIONDATE).ZANNOTATIONCREATIONDATE,
        modifiedDate: max_by(.ZANNOTATIONCREATIONDATE).ZANNOTATIONCREATIONDATE,
        isAllDay: false,
        isPinned: false,
        starred: false,
        timeZone: "America/Chicago",
        tags: (.[0].ZGENRE|ascii_downcase|split(" & ")|map(gsub(" ";"-"))),
        text: (
          group_by(.chapter)
          | map(
            [
              (.[0].ZFUTUREPROOFING5| h2)?,
              map(("* \(.ZANNOTATIONSELECTEDTEXT)"| split("\n") | map(select((gsub("[\r\n\t]"; "")? |length) > 3 )))
                | join(" ") | gsub("[\t\r]";" ") | gsub("[ ]{1,}";" ") )
            ] | flatten | join("\n\n"))
          | flatten | join("\n")
        )
      })
    | map (. + {text: ( "# \(.title)\n\nby \(.author)\n\(.text| remove_citations |gsub("[\\n]{2,}";"\n\n") )\n") })
    | sort_by(.modifiedDate)
    | { metadata: {version: "1.0"}, entries: map(del(.title,.author)) };
'

if ! command -v jq &>/dev/null; then
  echo "Download jq before continuing.. Aborting"
  exit 1
fi

cat $1 | jq "${JQ_FUNC} create_dayone_import" >$TMPDIR/ibooks.json

cd $TMPDIR && zip -q -r $DOWNLOAD_DIR/$ZIPFILENAME .

echo -e "
Done!
Import \e[0;49;33m${DOWNLOAD_DIR}/${ZIPFILENAME}\e[0m to Day One
" 3>&2 2>&1 >&3 3>&-
