#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1090
# Author: https://github.com/nntrn
# Repository: https://github.com/nntrn/queryibooks

set -e

PROG=queryibooks
VERSION=2.0

USER_IBOOKS=$HOME/Library/Containers/com.apple.iBooksX
QUERYIBOOKS_HOME="$HOME/.cache/queryibooks"

mkdir -p $QUERYIBOOKS_HOME

declare -A db_annotations
db_annotations[name]=annotations
db_annotations[path]="$(ls -1 $USER_IBOOKS/Data/Documents/AEAnnotation/*.sqlite)"
db_annotations[sql]="select * from ZAEANNOTATION
where ZANNOTATIONSELECTEDTEXT IS NOT NULL
and ZANNOTATIONSELECTEDTEXT <> ''
and ZANNOTATIONDELETED = 0;"

declare -A db_assets
db_assets[name]=assets
db_assets[path]="$(ls -1 $USER_IBOOKS/Data/Documents/BKLibrary/*.sqlite)"
db_assets[sql]="select * from ZBKLIBRARYASSET;"

HELP_TEXT='
Tool for extracting iBooks annotations

Usage:
  queryibooks [-f|--force] [-w|--write-to] [-c|--max-cache-age]
  queryibooks [-h|--help] [-v|--version]

Options:
  -f, --force             Run database update regardless of cache age
  -w, --write-to          Where to write output to
  -c, --use-cache         Use data from last run
  -c, --max-cache-age
  -h, --help
  -v, --version

Environment:
  QUERYIBOOKS_FORCE=1           # same as --force
  QUERYIBOOKS_USECACHE=1        # same as --use-cache
  QUERYIBOOKS_OUTPUT=<FILEPATH>
  QUERYIBOOKS_MAX_CACHE=<minutes>
'

JQ_FUNC='
  def map_annotations: {
    Z_PK,
    ZANNOTATIONCREATIONDATE,
    ZANNOTATIONASSETID,
    ZANNOTATIONSELECTEDTEXT,
    ZFUTUREPROOFING5,
    ZANNOTATIONNOTE,
    ZPLLOCATIONRANGESTART,
    ZANNOTATIONSTYLE,
    ZANNOTATIONTYPE,
    ZANNOTATIONISUNDERLINE
  };

  def map_assets:
    { ZASSETID, ZTITLE, ZAUTHOR, ZGENRE, ZSTOREID, ZSORTTITLE, ZASSETGUID };

  def map_json:
    reduce inputs as $s (.; .[input_filename|gsub(".json";"")|split("/")|last|ascii_downcase] += $s);

  def join_assets:
    INDEX(
      .assets[]; .ZASSETID) as $c
      | .annotations
      | map((map_annotations)+($c[.ZANNOTATIONASSETID]|map_assets)
    );

  def convertmacostime:
    map(
      with_entries(
        .key as $k|.value |= (
        if ($k|contains("DATE"))
        then ((.// 0) +978307200|strflocaltime("%FT%TZ"))
        else .
        end)
      )
    );

  def build: map_json|join_assets|convertmacostime;
'

_usage() {
  echo "$HELP_TEXT"
  exit 1
}

_version() {
  echo "$PROG-$VERSION"
  exit 0
}

log() {
  echo -e "$(date +'%F %X') $*" >>${QUERYIBOOKS_HOME}/log.txt
}

sync_database() {
  local DB="$1"
  if [[ -f $DB-wal ]]; then
    MOD_DB=$(stat -f %m "$DB")
    MOD_WALDB=$(stat -f %m "$DB-wal")
    if [[ $MOD_DB -lt $MOD_WALDB ]]; then
      sqlite3 "$DB" 'pragma wal_checkpoint;' ".exit" >/dev/null
      log "Sync ${DB##*/} $MOD_DB -> $(stat -f %m "$DB")"
      echo 1
    fi
  fi
}

querydata() {
  local -n data=$1

  TABLE="${data[name]}"
  DB_PATH="${data[path]}"
  SQL="${data[sql]}"
  SAVEFILE="${QUERYIBOOKS_CACHE}/${TABLE}.json"

  if [[ $QUERYIBOOKS_USECACHE -eq 1 ]]; then
    QUERYIBOOKS_FORCE=
  else
    QUERYIBOOKS_FORCE=$(sync_database "$DB_PATH")
  fi

  [[ ! -f $SAVEFILE ]] && QUERYIBOOKS_FORCE=1

  if [[ $QUERYIBOOKS_FORCE -eq 1 ]]; then
    sqlite3 -json "$DB_PATH" "$SQL" ".exit" >$SAVEFILE
    log "Fetch updated data from ${DB_PATH##*/}"
  fi
}

for i in "$@"; do
  case $i in
  -h | --help) _usage ;;
  -v | --version) _version ;;
  -f | --force) QUERYIBOOKS_FORCE=1 && shift ;;
  -w | --write-to) QUERYIBOOKS_OUTPUT=$2 && shift 2 ;;
  -c | --use-cache) QUERYIBOOKS_USECACHE=1 && shift ;;
  esac
done

if ! command -v jq &>/dev/null; then
  echo "Download jq before continuing.. Aborting"
  exit 1
fi

QUERYIBOOKS_ENV=$QUERYIBOOKS_HOME/.env
QUERYIBOOKS_CACHE="$QUERYIBOOKS_HOME"

if [[ $QUERYIBOOKS_USECACHE -eq 1 ]] && [[ -f $QUERYIBOOKS_ENV ]]; then
  source $QUERYIBOOKS_ENV
  log "QUERYIBOOKS_ENV=$QUERYIBOOKS_ENV"
else
  TODAY="$(date +%F-%H)"
  QUERYIBOOKS_CACHE="$QUERYIBOOKS_HOME/$TODAY"
  mkdir -p $QUERYIBOOKS_CACHE
fi

querydata db_assets
querydata db_annotations

jq -n "$JQ_FUNC build" ${QUERYIBOOKS_CACHE}/{assets,annotations}.json >$QUERYIBOOKS_CACHE/ibooks.json

if [[ -n $QUERYIBOOKS_OUTPUT ]]; then
  cp "$QUERYIBOOKS_CACHE/ibooks.json" "$QUERYIBOOKS_OUTPUT"
  echo "Saved to $QUERYIBOOKS_OUTPUT"
else
  cat $QUERYIBOOKS_CACHE/ibooks.json
fi

echo "QUERYIBOOKS_CACHE=$QUERYIBOOKS_CACHE" >$QUERYIBOOKS_ENV
